In [5]:
#hide
from fastbook import *
from IPython.display import display,HTML

In [6]:
from fastai.text.all import *
path = untar_data(URLs.IMDB)

In [7]:
import torch
from fastai.vision.all import *

# Set default device to MPS
defaults.device = torch.device("mps")

In [8]:
print(torch.backends.mps.is_available())

True

In [9]:
print(torch.backends.mps.is_built())

True

In [10]:
path

Path('/Users/aidardarmesh/.fastai/data/imdb')

In [11]:
files = get_text_files(path, folders = ['train', 'test', 'unsup'])

In [12]:
files

(#100000) [Path('/Users/aidardarmesh/.fastai/data/imdb/test/neg/1821_4.txt'),Path('/Users/aidardarmesh/.fastai/data/imdb/test/neg/9487_1.txt'),Path('/Users/aidardarmesh/.fastai/data/imdb/test/neg/4604_4.txt'),Path('/Users/aidardarmesh/.fastai/data/imdb/test/neg/2828_2.txt'),Path('/Users/aidardarmesh/.fastai/data/imdb/test/neg/10890_1.txt'),Path('/Users/aidardarmesh/.fastai/data/imdb/test/neg/3351_4.txt'),Path('/Users/aidardarmesh/.fastai/data/imdb/test/neg/8070_2.txt'),Path('/Users/aidardarmesh/.fastai/data/imdb/test/neg/1027_4.txt'),Path('/Users/aidardarmesh/.fastai/data/imdb/test/neg/8248_3.txt'),Path('/Users/aidardarmesh/.fastai/data/imdb/test/neg/4290_4.txt'),Path('/Users/aidardarmesh/.fastai/data/imdb/test/neg/10096_1.txt'),Path('/Users/aidardarmesh/.fastai/data/imdb/test/neg/11890_1.txt'),Path('/Users/aidardarmesh/.fastai/data/imdb/test/neg/2008_1.txt'),Path('/Users/aidardarmesh/.fastai/data/imdb/test/neg/472_4.txt'),Path('/Users/aidardarmesh/.fastai/data/imdb/test/neg/9876_2.txt'),Path('/Users/aidardarmesh/.fastai/data/imdb/test/neg/11402_1.txt'),Path('/Users/aidardarmesh/.fastai/data/imdb/test/neg/8487_1.txt'),Path('/Users/aidardarmesh/.fastai/data/imdb/test/neg/6648_2.txt'),Path('/Users/aidardarmesh/.fastai/data/imdb/test/neg/2780_4.txt'),Path('/Users/aidardarmesh/.fastai/data/imdb/test/neg/1789_2.txt')...]

In [13]:
txt = files[0].open().read(); txt[:75]

'Alan Rickman & Emma Thompson give good performances with southern/New Orlea'

In [14]:
spacy = WordTokenizer()
toks = first(spacy([txt]))
coll_repr(toks, 30)

'(#121) [\'Alan\',\'Rickman\',\'&\',\'Emma\',\'Thompson\',\'give\',\'good\',\'performances\',\'with\',\'southern\',\'/\',\'New\',\'Orleans\',\'accents\',\'in\',\'this\',\'detective\',\'flick\',\'.\',\'It\',"\'s",\'worth\',\'seeing\',\'for\',\'their\',\'scenes-\',\'and\',\'Rickman\',"\'s",\'scene\'...]'

In [15]:
first(spacy(['The U.S. dollar 1.00.']))

(#5) ['The','U.S.','dollar','1.00','.']

In [16]:
tkn = Tokenizer(spacy)
print(coll_repr(tkn(txt), 31))

(#139) ['xxbos','xxmaj','alan','xxmaj','rickman','&','xxmaj','emma','xxmaj','thompson','give','good','performances','with','southern','/','xxmaj','new','xxmaj','orleans','accents','in','this','detective','flick','.','xxmaj','it',"'s",'worth','seeing'...]

In [17]:
defaults.text_proc_rules

[<function fastai.text.core.fix_html(x)>,
 <function fastai.text.core.replace_rep(t)>,
 <function fastai.text.core.replace_wrep(t)>,
 <function fastai.text.core.spec_add_spaces(t)>,
 <function fastai.text.core.rm_useless_spaces(t)>,
 <function fastai.text.core.replace_all_caps(t)>,
 <function fastai.text.core.replace_maj(t)>,
 <function fastai.text.core.lowercase(t, add_bos=True, add_eos=False)>]

In [18]:
coll_repr(tkn('©   Fast.ai www.fast.ai/INDEX'), 31)

"(#11) ['xxbos','©','xxmaj','fast.ai','xxrep','3','w','.fast.ai','/','xxup','index']"

In [19]:
txts = L(o.open().read() for o in files[:2000])

In [20]:
txts[0]

"Alan Rickman & Emma Thompson give good performances with southern/New Orleans accents in this detective flick. It's worth seeing for their scenes- and Rickman's scene with Hal Holbrook. These three actors mannage to entertain us no matter what the movie, it seems. The plot for the movie shows potential, but one gets the impression in watching the film that it was not pulled off as well as it could have been. The fact that it is cluttered by a rather uninteresting subplot and mostly uninteresting kidnappers really muddles things. The movie is worth a view- if for nothing more than entertaining performances by Rickman, Thompson, and Holbrook."

In [21]:
def subword(sz):
    sp = SubwordTokenizer(vocab_sz=sz)
    sp.setup(txts)
    return ' '.join(first(sp([txt]))[:40])

In [22]:
subword(1000)

sentencepiece_trainer.cc(178) LOG(INFO) Running command: --input=tmp/texts.out --vocab_size=1000 --model_prefix=tmp/spm --character_coverage=0.99999 --model_type=unigram --unk_id=9 --pad_id=-1 --bos_id=-1 --eos_id=-1 --minloglevel=2 --user_defined_symbols=▁xxunk,▁xxpad,▁xxbos,▁xxeos,▁xxfld,▁xxrep,▁xxwrep,▁xxup,▁xxmaj --hard_vocab_limit=false

'▁A l an ▁R ick man ▁ & ▁E mm a ▁Th o mp s on ▁give ▁good ▁performance s ▁with ▁so u ther n / N e w ▁O r le an s ▁a c c ent s ▁in'

In [23]:
subword(200)

'▁A l an ▁ R ic k m an ▁ & ▁ E m m a ▁ T h o m p s on ▁ g i ve ▁ g o o d ▁p er f or m an ce'

In [24]:
subword(10_000)

"▁Alan ▁Rick man ▁ & ▁Emma ▁Thompson ▁give ▁good ▁performances ▁with ▁southern / N ew ▁O rleans ▁accents ▁in ▁this ▁detective ▁flick . ▁It ' s ▁worth ▁seeing ▁for ▁their ▁scenes - ▁and ▁Rick man ' s ▁scene ▁with ▁Hal"

In [25]:
toks200 = txts[:200].map(tkn)
toks200[0]

(#139) ['xxbos','xxmaj','alan','xxmaj','rickman','&','xxmaj','emma','xxmaj','thompson','give','good','performances','with','southern','/','xxmaj','new','xxmaj','orleans'...]

In [26]:
num = Numericalize()
num.setup(toks200)
coll_repr(num.vocab,20)

"(#1984) ['xxunk','xxpad','xxbos','xxeos','xxfld','xxrep','xxwrep','xxup','xxmaj','the','.',',','and','a','to','of','i','it','is','in'...]"

In [27]:
nums = num(toks)[:20]; nums

TensorText([  0,   0, 234,   0,   0, 199,  64, 731,  29,   0, 122,   0,   0, 943,  19,  20, 944, 294,  10,   0])

In [28]:
' '.join(num.vocab[o] for o in nums)

'xxunk xxunk & xxunk xxunk give good performances with xxunk / xxunk xxunk accents in this detective flick . xxunk'

In [29]:
stream = "In this chapter, we will go back over the example of classifying movie reviews we studied in chapter 1 and dig deeper under the surface. First we will look at the processing steps necessary to convert text into numbers and how to customize it. By doing this, we'll have another example of the PreProcessor used in the data block API.\nThen we will study how we build a language model and train it for a while."
tokens = tkn(stream)

In [30]:
tokens

(#90) ['xxbos','xxmaj','in','this','chapter',',','we','will','go','back','over','the','example','of','classifying','movie','reviews','we','studied','in'...]

In [31]:
bs,seq_len = 6,15
d_tokens = np.array([tokens[i*seq_len:(i+1)*seq_len] for i in range(bs)])
df = pd.DataFrame(d_tokens)
display(HTML(df.to_html(index=False,header=None)))

In [32]:
nums200 = toks200.map(num)

In [34]:
#hide
nums200

(#200) [TensorText([   2,    8,    0,    8, 1442,  234,    8,    0,    8,    0,  199,   64,  731,   29,    0,  122,    8,  253,    8,    0,  943,   19,   20,  944,  294,   10,    8,   17,   25,  338,  408,
              28,  102,    0,   12,    8, 1442,   25,  160,   29,    8,    0,    8,    0,   10,    8,  163,  320,  164,    0,   14, 1443,  295,   77,  254,   61,    9,   27,   11,   17,  296,   10,
               8,    9,  110,   28,    9,   27,  650, 1134,   11,   31,   42,  321,    9,  732,   19,  152,    9,   32,   22,   17,   23,   36, 1135,  123,   33,  101,   33,   17,   81,   38,   87,
              10,    8,    9,  180,   22,   17,   18,    0,   49,   13,  264, 1444, 1445,   12,  835, 1444,    0,   76,    0,  188,   10,    8,    9,   27,   18,  338,   13,    0,   54,   28,  132,
              79,   90,  456,  731,   49,    8, 1442,   11,    8,    0,   11,   12,    8,    0,   10]),TensorText([   2,   16,   38,  140,   20,   27,   12,   16,   73,   36,  255,   28,   20,   27, 1136,   10,   16,   68,   36,  142,   60,  156,   14,    8, 1137,   93,   16,   48,   36,   46,   20,
             651,   12,  109, 1446,    0,   10,   16,   48,   36,   46,   14,    0,  652, 1136,   93,   16,   48,   36,  457,  102,  733,   10,    8,  133,   68,   16,  161,   14,    8,    0,   69,
              16,  264,  161,   14,    8,    0,   58,    9,    8,  583,    8, 1447,   55,    8,    0,   12,    9,    8,  583,    8, 1447,   43,    9, 1448,   16,    0,   10,    8,  409,    9,    8,
            1449,    8, 1450,   48,   36,  457,    9,    8,  652,  733,   56,   46,   88,   10,    8, 1451,   16,  131,   36,  584,    9,    8,    0,  945,   77,  254,   61,   10,   16,  205,   33,
             101,  836,   14,    9,    8,  583,    8, 1447,   12, 1138,  585,  533,   12,  339,  297, 1452,   54,   59,   18,   13,  297,    0,   10,    8,   22,   18,   47,   10]),TensorText([   2,    8,   19,    8,    0,    8,    0,   11,    9, 1453,   12,    0,    8,    0,    8,    0,   41, 1139,    8,    0,   39,    0,   13, 1140, 1454,   15,  340,   26,    0,    0,   56,
              14,   94,  244,  322,   14,    0,   12,    0,   19, 1455,    0,   10,    8,   53,    0,   12,   82,    0,   18,  380,   12,  489, 1141,   29,    0,  533,   10,   24,   21, 1456,   21,
              18,   62, 1444,   11,  946,   12,  534,  256,   27,   60,   62,    0,    0,    0,   22,  586,   13,  734,   15,  653,   58, 1457,   56,   14,   94,  244,  322,   14,  587,    0,   12,
               0,   11,  117,  735,    0,  458,   14,   53,    0, 1142,   10,    8,   19,    0,   29,  654,   11,   20,  141,   68,   37,    9,    0,    0,   26,    0,   15,    9,    0,    8,  947,
               8,    0,   11,   12,  535,   34,   20,  103,   11,   16,  131,  410,  120,  235,  115,   15,   53,    0,   10,    8,    0,   11,   54,    9,  490, 1143,   20,  837,   15, 1453,    0,
              11,  121,  123,  152,    9,    0,   12,    0,    8,    0,    8,    0,   25,   21,    0,   21,   58,    8,    0,    8,    0,   25,   21,    0,    0,    8,    0,    8,    0,   21,   22,
              18,  535,   34,    9,  189,   15,    9,  190,  491,   10,    8,   71,  736,   18,  838,   10,   24,    8,  459,   41,    0, 1458,   21, 1456,  492,    8,    0,    8,    0,   21,   41,
              21, 1456,  492,    8,  257,    8,    0,   21,   39]),TensorText([   2,    8,   20,   32,   18,    0,  411,   29,   21,    0,    0,    0,    8,    0,   66,    0,    0,    8,    0,   21,   12,  276,  154,  839,   13,  277,   14,   37,    0,   19,    9,
             129,   15,  102,    7,  493,    0,   10,    8,  125,   11,  276,  154,   43,   78,  341,  323,    0,  324,   17,  236,   14,   91,  494,   61,   25,    0,   10,    8,  412,   11, 1144,
              32,   70, 1145,   12,   35,   43,  948,   14,  104,   13, 1146,   32,  323,  212,   21,    0,    8,    0,    0,    8,    0,   21,   92,  298,   14,   38,   13,  121,    0,   10,    8,
             840,   11,   16,  413,    0, 1145,   31,   28,    9,  340,   26,    0,   63,   59,   20,   18,   30,   13,  495,   10,    8,  163,    7,  493,  841,   11,  219,   11,   43,   36,    9,
            1459,   15,    9,  171,   32,  842,  323,   56,    9,    0,    0,  117,    0,  838,    0,  342,   10,   24,    8,   33,   28,    9,   32,   11,   17,   25,   60,    9,    0,   15,    8,
             496,    8,  588,   10,    8,   20,   18,   13,    7,  589,  495,   11,   33,    8,  536,    8, 1460,  237,   60,   33,   98,   46,    8,  588,   33,    8, 1461,    8,    0,   10,    8,
              19,   77,  129, 1147,   92,   40,  146,   46,    8,  588,   10,    8,   40,   25,  949,    9,    0,   11,   70,    9,  381,  950,    0,   12,  655,   12,   18,   56,   36,   67,  460,
              19,  115,  129,   41,    0,   88,   34,   20,   11,   16,  200,   62,    8,  308,    8,  353,    0,   12,   89,   43,  497,   14,  126,  163,  537,   15,  188,   50,   39,   10,    8,
               9,  153,  189,    8,  588,   23,   13,    8,    0,    8,  590,  435,   12,  414,   46,    9,  265,   34,    9,    8,  843,    8,  951,    0,    0,    0,   10,    8,  844,   11,  845,
              65,  105,  258,   14,    0,    9,  538,   28,    8, 1460,   19,    9,  952,   18,   56, 1462,   10,    8,  120,  178,   58,  278,   70,    8,  536,    8, 1460, 1463,  354,   45, 1464,
              50,   50,    8,   40,   23,   13,  461,  258,   66,   31,  410,   36,   13,  953,  435,   58, 1464,  496,   10,   24,    8,   19,    0,   14,    9,  213,  539,   11,    8,  496,    8,
             588,   25,  737,   23,   19,   77,  129,   46,   20,   32,   10,    8,   17,   25,  355,   22,    9,   32,  842,   43,  214,    0,   19,   34,    9,  846,    0,   60,    0,    0,    9,
             737,   15,    7,    0,   11,   36,    8,  588,   10,    8,  588,   23,  245,   19,    8,    0,   11,    7, 1465,   41,   36,    8,    0,   39,   49,   13,    0,    0,   29, 1466, 1467,
             841,  323,   36,   13,  656,   15,  382,   29,    0,   10,    8,  219,   11,  954,   14,  108,    0,   11,   61,  214,  279,    8,  588,   41,  118,  127,  847,  342,   39,   75,    0,
               0,  323,   51, 1468,   12, 1468,   12, 1468,   14,    0,   13,  955,   41,   14,   77,    0,   39,   12,  120,  956,    0,  102, 1469,   58,    0,   19,    9,  957,   10,    8,   19,
             105,  657,   11,   46,    8,  540,    8,    0,   41,   51,   23,  958,  279,   49,    0,    0,   69, 1470,   29,    0,   39,   40, 1471,  458,   14,    0,   10,    8,   19,    9,   27,
              44,  246,  132,  220, 1147,   66,  105,   90, 1472,    8,  496,    8,  588,   23,  245,   10,   24,    8,   93,    9,   32,    0,  221,   77,    0,   14,  153,  353,   11,   17,   25,
              46,   13,  353, 1473,   33,    0,   57,  238,   57,  181,  738,   58,  238,   29,   13, 1466,  658,    0,   10,    8,  133,   36,  124,    0, 1474,   11,  659,    0,   12,    9,    8,
               0,    0,  182,   35,  175,   52,   17,   55,   50,   55,   50,    8,  959,   57,   65,  259,  106,   12,  383, 1148,   11,   93,    9,  195,   18,  848,    0,  356,   11,   16,   48,
              30,  541,  266,  104,   17,   10,    8,   17,   25,   56,   13,  462,   12,  848,  591,   10]),TensorText([   2,   16,   82,  739,   34,   76,   78,   64,  154,   12,   34,  848,    0,   10,    8,   71,    0,   18,   14,  309,   99,   51,  176,   14,   91,  150,  154,   14,  592,  102,   80,
              26,   12,  322,   26,    0,   10,   24,   16,  124,  176,   14,  542,   99, 1149,  102,   80,   34,  543,   11,   12,  176,   14,    0,    9,  180,   22,    9,  157,  122, 1150,   15,
             163,  543,  154,  215,   30,   94,  357,   29,   17,   28,   78,  206,   10,    8,   89,  131,  280,   63,   51,   35,   43,   12,  131,  736,   29,   63, 1475,   26,   12,    0,   10,
              24,    8,   20,   32,  660,  740,   95,    9,  543,    0,   10,   24,    8,    9,  157,   12,  491,   18,    8,  415,    8, 1476,   10,    8,   17,   25,  413,   13,   74,  960,   69,
               9,  491,   18,  124,    9,  157,   10,    8,  281,   40,  498,  127,  741,    0,   10,    8,   40,  143,   30,   94,  115,   10,    8,   45,  358,    9,  299,   26,    8,  415,    7,
            1476,   10,    8,   12,   54,   35,   91,  191,  310,   49,  111,   11,  593,   17,   10,   24,   16,  594,   30,  147,  191,   60,    9,  110,   26,  595,   38,  463,   10,   16,  200,
              13,  130, 1477,   49,  112,   98,    9,  157, 1143,   14, 1478,   19,   14,    9,  267,  268,   25,  359,   69,   97,   18, 1151,   12,  961,   10,    8,  163,  206,    0,  742,   43,
              13,  130,    0,   12,  282,  147,  138,   60,    9,  661,   15,  436,   15,    8,  849,   10,    8, 1476,   10,    8,  281,   40,  143,   94,    0,  309,   10,   24,    8,  244,  463,
              10,    8,   17,   25,  356,   26,   48,   30,  283,  155,   80,   34,   17,   10]),TensorText([   2,    8,   69,   35,  146,   52,    9,  544,   12,  235,  437,   60,   17,   62,  962,  343,  438,   15,   27,  499,   14,  436,   90,   61,   35,   94,  196,   10,    8,  128,  201,
             281,   16,  235,    9, 1479,   28,    9,  105,   27,  500,   21,    0,   21,  239,   33,   59,   75,  127,  113,   15,   20,  459, 1480,   60,    9,  190,   80,   29,  276,    0,  963,
              22,   83, 1152,  964,   19,  850,   10,    8,  219,   11,  743,  437,   60,   22,   27,  196,   16,  126,   16,  192,   20,   42,   12,   36,   22,   42,   12,   22,   27,   18,   67,
             360,   61,   42,   68,  384,   13,   27,   29,   22,  459,   68,   37,   60,   10,   16,  131,   37,  545,   11,   16,  464,   79,   15,   13,    0,  438,  744,   12,   35,   94,   22,
              19,   20,   27,   14,   65,    0,   10,    8,  219,   11,   59,   18,   79,  437,  965,    9,    0,   12,  745, 1481,   33,    9,  966,  160,   15,    9,   99,  117,  501,  357,   49,
               9,    0,   52,    9,  416,   15,    9,   32,  131,    0,   14,   10,    8,    9,   27,  124,   70,    9,  167,  837,   15,  967,  156,  851,   44,   48,   36,    0,   14,   38,   65,
             846, 1482,   11,   19,   20,  385,   17,   18,   19,  180,   13,    0,   10,    8,    9,  105,   27,   16,   48,   36,  142,   76,   70,   22, 1152,    0,  417,   22,    0,  386,   19,
               9,   27,   12,   16,   91,    9,  746,   28,   20,   42,   18,  968,  100,   11,  151,   17,   23,   56,   36,    9,   27,   16,   23,  747,   10]),TensorText([   2,    8,    0,  969,   55,   50,    8,   16,  137,  546,   31,   67,   28,    9, 1153,   25,   22,   25,   56,  129,  100,  547,   14,   37,    0,  465,   66,    8,   35,   84,  748,
               9,  171,    9, 1483,    0,  749,   93,   17,   23,    0,  167,  113,   12,    7,  247,  650,   11,   31,   22,   25,   87,  216,  311,   11,   45,    9,  418,  502,   14,   37,   13,
             130,  360,  548,   11,   36,   67,   79,    0,   50,    8,  844,   11,    9,  125,   27,   83,    9,  852,   15,    8,  419,    8,    0,   26,   13,  148,   51,   81,   67,  114,    0,
               0,   19,    0,    0,  298,    0,   50,   26,   22,   20,   42,    0,    0,   11,   45,   59,   23,   77,   72,    0,   72,   19,  191,   22,  596,   11,   17,   56,  344,  662,   10,
              24,    8,    0,   16,   82,  192,   20,  311,   69,   16,   23,  853,   11,   31,   49,  128,  463,  117,   13,  549,  284,   15,    9,  171,   16,  358,  117,    0,   10,    8,   14,
              88,   11,   59,   18,   77,  418,   14,    8,    0,    8,  466,   11,   56,   13,    0,    0,   22,   92,   30,    0,  115,    0, 1147,   10]),TensorText([   2,    8, 1484,    0,   41,   29,    0,   21, 1485,   21,  300,    0,    0,    0,   11,   21,    0,   21, 1486,   13,  277,   15,    0,   14,    0,  172,   12,  131,  207,  387,  123,
             108,  970,  173,   31,    9,  439,    0,    0,  345,   12,    8, 1154,    8,    0,   11,   51,    0,   53,  503,   19,  221,  202,  160,   11,  124,  750,   62,  854,  953,  388,   10,
              13,    0,   11,   14,   37,  208,   11,   31,    9,   79,    0,   21,  663,   21,   11,  116,  127,  240,  342,   11,   18,   13, 1487,    0,  664,   10,   16,    0,   35,  104,   22,
             239,   10,   41,  260,  222,  122,  168,   39]),TensorText([   2,    8,   69,    8,  325,   18,  301,   14,    0,   61,   62,   21,  855,  467,   21,   18,   46,   11,   44, 1155,   45, 1488,   11,    0,   17,  236,  971,  657,   19,    9, 1489,
              15,    9,    0,   21,  856,   21,   10,   24,    8,  220,   11,  115,  856,    0,  209,  301,   14,    0,   19,   53,    0,   52,  202,  972,   10,    8,  208,   11,   44, 1490,   63,
              19,    0,   12, 1156,  857,  492,   17,   25,   36,   46,   44,   43,   41,    0,    0,   39,    0, 1491,   51,  120,   38,   13,    0,   10,   24,    8,  844,   11,   54,   35,   43,
              13,  856,   35,  126,   47,   60,    8,    0,   12,    8,  353,   12,    8,    0,   12,   15,  302,   35,  175,  973,   85,   14, 1492,   29, 1493,  974,   12,   13,    0,    0,   15,
             136,   10,    8,    0,  163,  188,   11,   46,   11,   47,  161,  665, 1494,  437,   11,    0,   55,   24,    8,  844,   11,   35,    0,  209,   29,   13,    0,   47,    9,   80,   10,
               8,   35,   43,   56,   13,    0,  468,   15,   13,   35,   26,  126,   26,   61,   11,   22,   25,  112,   17,   18,   11,    0,   47,   10,   24,    8,   12,   15,  302,   35, 1495,
              11,   46,  238,   51,  120,    0,  178,   11,   31,   35, 1495,    0,   17,   25,   46,  469, 1494,  437,   11,    0,   10,    8,   12,   35,  175,  343,   10,    8,   22,   18, 1496,
              10,   24,    8,   12,   15,  302,   35,   84,  751,  492,   35,  175,   13,    0,   10,   13,    0,   51,  858,   80,   14, 1497,  185,   10,    5,  139,  597,  666, 1157,   40,   92,
              30,    0,    0,   10,    8,   12, 1157,   40,   92,   30, 1495,   58,    0,    0,   93,   40,    0,   13,    0, 1498,    0,   10,   24,    8,   12,   35, 1492,   13, 1158,   26,  138,
             859,  975,  492,    8,    0,    8,    0,   10,    8,  101,   11,   16,  594,   30,   67,  739,    8, 1139,    8,    0,   10,    8,  550,    8,  976,   70,  752,    9, 1499,   34,    9,
             326,  463,   10,   24,    8,   20,   27,   18,   13,    0,   15,   13,    8,    0,  234,    8,    0,  438,  975,   41,   19,  105,  657,    0, 1159,   15,  136, 1458,   21,  667,   11,
              22,   25,   61,   16,   68,   37,   46,   54,   16,   23,   13,  856,   10,   21,    8,   31,  213,   99,   12,  213,    0,   19,   20,  385,   84,   36,  384,    9, 1160,   15,    0,
              10]),TensorText([   2,    8,    0,  504,    0,    8,    0,    8,    0,   18,    0,   63,   15,  327,   29,   20,    0,  860,  285,  551,   12,    0,  103,   22,    0,   57,   13, 1161,  505,   15, 1162,
               0,   10,    8,    0,  296,   14,   38,    0,    0,   80,   12, 1500,   28,    9,  125,  203,   33, 1501,    8, 1154,    8,    0,   12,    8,    0,    8,    0,  261,  130,  598,   95,
             102,  753,   11,    0,  303,    0,   12,  257,    0,   10,   24,    8,    0,    0,    0,    8,    0,   21,    0,   21,    8,    0,  586,   33,   62,  861,  148,   34,   13,    0,  361,
              22,  328,   74,   12,  321,   53,  420,  279,   19,    9,  957,   10,    8,   40,    0,   57,  421,   12,  735,  599,   63,   14,  470,    9,  420,   15,    9,  944,   51,  279,   53,
              10,    8,    0,   15,  551,   43,    0,   14,  506,  111,   57,  241,   14,    9,  600,   15,    9,  977,   51,   70,   87, 1502,   14,  181,  754,   31,   68,   30,   35,  126,   19,
               9,  154,  422,  668,   89,   38,    8,    0,    0, 1475,  346,    9, 1163,   41,   51,  248, 1164,   22,  755,   13,    0,  183,   14,    9,  471,   23,   13,  304,  507,   39,  182,
              13,  756,   15,  551,    0,   12,    0,  118,   61,  227,   14,  203,   10,    8,  304,    0,   55,    8,   35,  143,   91,   17,   10,    8,   17,   25,   47,   15,   22,   12,   79,
              10,   24,    8,    0,    8,    0,   25,  440,  197,   92,   13,  259,  361,   15,    0,    0,   14,    9,    0,   31,    9,  601,   18,    0,   12,    0,   12,   17,    0,    9,   32,
              15,  109, 1503,   12, 1165,   10,    8,   33,    8,    0,   11,    8,    0,    8,    0,   18,    9,  169,  158,   19,    9,   32,    0,   14,    0,  150, 1504,   33,   40,    0,   57,
               0, 1505,   14,    0,   10,    8,  163,    0,  959,    8,  669,    0, 1166,   19,    0,   12, 1167,  324,  109,  552,  862,   10,    8,  161,    8,  504,  167,    8,    0,   10]),TensorText([   2,    8,  204,   27,  119,  140,   10,    8,  204,  106,  100,   10,   16,   84,   36,  384,   13,   27,  312,  128,   20,   10,    8,  132,   14,   91,   10,    8,   77,  106,   52,
               0,  757,   41,  164,   39,  143,  146,   28,  181,  361,   10,   16,    0,  457,   51,   23,  213,  244,   14,  214,  261,  322,   95,   20,   27,   10,   24,    8,   16,  137,  546,
              28,    8, 1506,    8,  758,   10,    8,  313,   37,  759,   66,   16,   84,   36,  384,  112,    0,    5,  139,    0,    7,    0,   53,    0,  313,   37,   14,    0,  755,    9,  361,
              50,   24,    8,    9,    0,   19,    9,   27,   66,  423,   44,  121,  836,   14,    5,  139,  602,   10,   24,    8,   33,   28,    9,    7,  760,    7,  148,   66,   61,   13,  761,
              50,    8,   40,  121,   37,  261,   34,   13,  761,   12,  553,   59,   50,   16,   84,   91,  111,  117,   79,  863,   52,    0,  264,   90,  106,   10,   24,    8,  472,  473,   96,
               8,   48,   36,  603,   66,   48,    7,   36,    7,  587,   50]),TensorText([   2,   16,   23,  948,   14,  104,   20,   32,   28,   71,    8,  210,    8,    0,    8,    0,  762,   10,    8,   20,   32,   18,   61,   18,  381,   29,    8,  976, 1168,   11,  239,
              15,    0,   63,    9,  169,  129,   63,   15,  236,  249,   58,  978,   89,   68,  264,    0,   60,  112,   17,   18,  238,  310,   25, 1459,   10,    8,   20,   32,  328,  172,    9,
               0,   15,    8,    0,   11,    8,    0,   12,    0,   17, 1507, 1159,   34,    8,  435,    8,    0,   10,    8,   19,    9,  957,   15,  242,   45,    8, 1508,  328,   14,  150, 1509,
              14,  114,    9,    0,   15,    8,  435,    8,    0,   63,   14,   37,    0,   56,   93,   44,   43,  242,  102,  361,   19,   13,    0,    0,   10,    8, 1508,  154,  604,    0,  441,
               9,   32,   12,   92,   36,  119,   67,  763,  311,   54,    9,  467,   18,  117,    0,   93,   15,   13,    7,    0,    0,   10,    8,    0,   11,   40,  120,    0,    9,    0,   15,
               9,    0,  764,   10,    8, 1508,  328,   14,  150, 1509,   14,  979,    0,  974,   14, 1510,   53,  670,    0,   19,   20,   32,   15,  605, 1511,   10]),TensorText([   2,    8,  101,   17,   18,   60,  222,   11,    5,  139,  597,  240,   19,    9, 1169,   12,   89,   38,  508,    0,    0,    9, 1512,    0,  300,    0,   50,   50,    8,   31,  554,
              89,  151,  474, 1170,   22, 1513,    0,   11,  314,  382,   43,  151, 1514,  555,  105,  951,   11,   12,  241,  329,   11, 1515,   11,  659,  671,  606,    8,  850,    0, 1171,  314,
             382,   43,  151,  241,    9,  362,  162,   15,    9,  836,   50,    8,    0,   19, 1516,  314,    0,    0,   22,  146,   46,   44,  175,   57,    8, 1517, 1172,  460,    0,   29,    9,
               0,   12,  765,   10,    8,    0,   99,  151,    0,    0,   14,  507,   11,   77,    0,    0,   11,    0,   11,   58,    0,    0,   10,    8, 1518,  151,  237,   12, 1519,  766,   10,
               8,  607,   16,  161,   34,   66,    8,   19,  362,   20,  507,   23,  245,   34,   13, 1520,  864,   26,  865,  363,  243,  177, 1173,   11,  164,   11,   12,   77,  153,  315,  223,

In [35]:
dl = LMDataLoader(nums200)

In [36]:
dl

In [37]:
x,y = first(dl)
x.shape,y.shape

(torch.Size([64, 72]), torch.Size([64, 72]))

In [38]:
' '.join(num.vocab[o] for o in x[0][:20])

'xxbos xxmaj xxunk xxmaj rickman & xxmaj xxunk xxmaj xxunk give good performances with xxunk / xxmaj new xxmaj xxunk'

In [39]:
' '.join(num.vocab[o] for o in y[0][:20])

'xxmaj xxunk xxmaj rickman & xxmaj xxunk xxmaj xxunk give good performances with xxunk / xxmaj new xxmaj xxunk accents'

In [40]:
get_imdb = partial(get_text_files, folders=['train', 'test', 'unsup'])

dls_lm = DataBlock(
    blocks=TextBlock.from_folder(path, is_lm=True),
    get_items=get_imdb, splitter=RandomSplitter(0.1)
).dataloaders(path, path=path, bs=128, seq_len=80)

In [41]:
dls_lm.show_batch(max_n=2)

xxbos xxmaj the book , while not particularly great , was decent , but this movie completely changes it . a lot of the elements of the story are consistent between the book and the movie , but xxmaj dr . xxmaj ross ' character goes from a creatively written character who lives for money and ends up causing the volcanic eruption with her greed to a heart - on - her - sleeve damsel in distress who wo n't
extent but like other comments have stated this is not for everyone . xxmaj there are cruel and upsetting scenes involving the young female characters and it would take a hardened heart to not to flinch or be moved by what the characters have to endure . xxmaj xxunk scientific experiments , limbs are torn off , there are scenes of implied sexual abuse . xxmaj but this is not some misogynistic experience of sadism , at its centre it
xxmaj the book , while not particularly great , was decent , but this movie completely changes it . a lot of the elements of the story are consistent between the book and the movie , but xxmaj dr . xxmaj ross ' character goes from a creatively written character who lives for money and ends up causing the volcanic eruption with her greed to a heart - on - her - sleeve damsel in distress who wo n't do
but like other comments have stated this is not for everyone . xxmaj there are cruel and upsetting scenes involving the young female characters and it would take a hardened heart to not to flinch or be moved by what the characters have to endure . xxmaj xxunk scientific experiments , limbs are torn off , there are scenes of implied sexual abuse . xxmaj but this is not some misogynistic experience of sadism , at its centre it is

In [42]:
learn = language_model_learner(
    dls_lm, AWD_LSTM, drop_mult=0.3, 
    metrics=[accuracy, Perplexity()], cbs=[MixedPrecision()]).to_bf16()

In [60]:
learn.save('1epoch')

Path('/Users/aidardarmesh/.fastai/data/imdb/models/1epoch.pth')

In [ ]:
learn.unfreeze()
learn.fit_one_cycle(10, 2e-3)

/Users/aidardarmesh/epam/dl-practitioner/.venv/lib/python3.11/site-packages/torch/amp/autocast_mode.py:270: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn(
/Users/aidardarmesh/epam/dl-practitioner/.venv/lib/python3.11/site-packages/fastai/callback/fp16.py:47: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  self.autocast,self.learn.scaler,self.scales = autocast('cuda', dtype=dtype),GradScaler('cuda', **self.kwargs),L()